### ISSUE TITLE
Crash when exiting settings (Linux64)

### ISSUE THREAD

**Issue by Pnumekin** [HFScode/zspin#39]
If I enter settings with ctrl+s and then exit to Main menu, Zspin show a black screen and don't respond anymore.
I need to alt+F4 to exit and start zspin again.

**Comment by vikbez** [comment]
paste console log (ctrl+d, console tab) (open console before making the bug happen)

**Comment by Pnumekin** [comment]
Console cleared before the bug happen. But this warning popup when I enter the settings, not when exiting.

pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details.

**Comment by vikbez** [comment]
this error is not related to your bug
are you sure that zspin does not respond anymore at settings exit ? up/down/back does nothing ?

**Comment by Pnumekin** [comment]
That's what i'm thinking.
up/down/enter doesn’t respond but exit quit zspin normaly
(Haven't tested this one, sorry)

**Comment by vikbez** [comment]
did you tried to reset your settings at the botton of settings page ?
did you tried to reset your settings by deleting `~/.config/app-name/settings.json` ?

**Comment by Pnumekin** [comment]
1) Reset everything at the bottom
2) Choose French
3) Define my path
4) Change the "Back" key (because shift doesn’t work)
5) This error screen :
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Calling a callback of released renderer view
    at BrowserWindow.ret (/home/pnume/zspin-linux-x64/resources/atom.asar/browser/lib/rpc-server.js:112:21)
    at emitOne (events.js:82:20)
    at BrowserWindow.emit (events.js:169:7)
    at callFunction (/home/pnume/zspin-linux-x64/resources/atom.asar/browser/lib/rpc-server.js:138:18)
    at EventEmitter.<anonymous> (/home/pnume/zspin-linux-x64/resources/atom.asar/browser/lib/rpc-server.js:234:14)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/home/pnume/zspin-linux-x64/resources/atom.asar/browser/api/lib/web-contents.js:101:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

This error popup only the first time, if I do the same without reseting my settings, it wont popup.
If I don't change my "Back" key,I can't go back and I'm stuck in black screen without the error message.

**Comment by vikbez** [comment]
can you try again with 0.3.2 ?
now you can launch zspin directly with parameter --debug (or use --help for options)

**Comment by Pnumekin** [comment]
Bug is still present with 0.3.2, I will launch it with --debug ans post here the result.

**Comment by Pnumekin** [comment]
Here is my log, but there is nothing new :(
http://pastebin.com/TRzZrfV9
